common:
  log_level: INFO
  seed: 1
  deterministic: False
  implement_layer: [SMore_seg]
  plugin_layer: []

other:
  mean: &mean [0.485, 0.456, 0.406]
  std: &std [0.229, 0.224, 0.225]

  scale: &scale 1.0
  workers: &workers 2
  class_weights: &class_weights [0.1, 1, 1,1]
  ignore_label: &ignore_label 255
  num_classes: &num_classes 4
  max-iter: &max-iter 13000
  batch_size: &batch_size 2
  val_batch_size: &val_batch_size 1
  input_size: &input_size [2437, 4452]
  lr: &lr 0.01
  rotate_angle: &rotate_angle [-180,180]
  label_map: &label_map
    - bg
    - heibaixian
    - bianxing
    - pengshang

  category_map: &category_map
    - [bg]
    - [heibaixian, yayin]
    - [bianxing]
    - [pengshang]


  color_map: &color_map
        - [0,0,0]
        - [128,0,100]
        - [255, 0, 0]
        - [0, 255, 0]


data:
  train_data:
    batch_size: *batch_size
    workers: *workers
    dataset:
      type: LabelMeDataset
      category_map: *category_map
      delimiter: '||'
      data_path:
        - root: /data
          path: /home/jiachen/data/seg_data/hebi/new_PSA_gw3/codes_roi2bins/till0322_PSA_gw3_train.txt   #qwbx_PSA_gw3.txt

    transform:
      - &cvtColor
        type: CvtColor
        mode: BGR2RGB
        # 切掉上下左右的冗余
      # - &roicrop
        # type: ROICrop
        # roi: *roi
      - &resize
        type: Resize
        output_size: *input_size
      - type: RandomHorizontalFlip
        prob: 0.5
      - type: RandomVerticalFlip
        prob: 0.5
      # - type: SMore_seg::RandomScale
        # scale: [0.8, 1.25]
        # aspect_ratio: [0.8, 1.25]
      - type: RandomRotation
        prob: 0.5
        angle: *rotate_angle
      # - type: SMore_seg::RandomCrop
      #   output_size: *input_size
      # - type: RandomApply
      #   p: 0.3
      #   transforms:
      #     - type: PhotoMetricDistortion
      - &normalize
        type: Normalize
        mean: *mean
        std: *std
        scale: *scale
      - &toTensor
        type: ToTensor

  eval_data:
    batch_size: *val_batch_size
    workers: *workers
    dataset:
      - type: LabelMeDataset
        data_name: val
        category_map: *category_map
        delimiter: '||'
        data_path:
          - root: /data
            path: /home/jiachen/data/seg_data/hebi/new_PSA_gw3/codes_roi2bins/test.txt
        category_map: *category_map
    transform:
      - *cvtColor
      # - *roicrop
      - *resize
      - *normalize
      - *toTensor


  test_data:
    batch_size: *val_batch_size
    workers: *workers
    dataset:
      - type: LabelMeDataset
        data_name: test
        category_map: *category_map
        delimiter: '||'
        data_path:
          - root: /data
            path: /home/jiachen/data/seg_data/hebi/new_PSA_gw3/codes_roi2bins/test.txt
        category_map: *category_map
    transform:
      - *cvtColor
      # - *roicrop
      - *resize
      - *normalize
      - *toTensor

model:
  type: EncoderDecoder
  backbone:
    type: HRNetW18SmallV2
    pretrained_weights: /home/jiachen/project/pretrain/hrnet_w18_v2.pth
  head:
    type: FCNHead
    num_classes: *num_classes
    in_index: [0, 1, 2, 3]
    input_transform: resize_concat
    losses:
      - type: Dice
        num_classes: *num_classes
        weight: 0.5
        ignore_label: *ignore_label
        class_weights: *class_weights
      - type: CE
        num_classes: *num_classes
        weight: 0.5
        ignore_label: *ignore_label
        class_weights: *class_weights

train:
  type: SimpleTrainer
  with_amp: True
  max_iter: *max-iter
  ckpt_freq: 1000
  print_freq: 100
  optimizer:
    type: SGD
    lr: *lr
    weight_decay: 0.005
    momentum: 0.9
  lr_scheduler:
    type: WarmupCosineLR
    max_iter: *max-iter
    warmup_iter: 0

eval:
  type: SimpleInference
  output_post_processors:
    - type: RemoveShortDefect
      length_threshold: [100, 60, 60]
      num_classes: *num_classes
  evaluators:
    - type: PixelBasedEvaluator
      num_classes: *num_classes
      label_map: *label_map
      ignore_label: *ignore_label
    - type: InstanceBasedEvaluator
      num_classes: *num_classes
      label_map: *label_map
  visualizer:
    type: ConcatVisualizer
    painters:
      - type: ylMaskPainter
        num_classes: *num_classes
        label_map: *label_map
        ignore_label: *ignore_label
        color_map: *color_map
        mask_weight: 0.3
        gamma: 10
        original_image: True


deploy:
  type: OnnxDeploy
  shapes: [1, 3, 4452, 2437] # 和input_size相反

analyze:
  type: TransformAnalyzer
  sample: 50
  num_classes: *num_classes
  label_map: *label_map
